#! /bin/sh

sxhkd &
setxkbmap -layout 'us' && setxkbmap -option 'grp:shift_caps_toggle' &
nm-applet &
#redshift-gtk &
#mopidy &
#picom -b --config ~/.config/picom.conf &
picom -b --config ~/.compton.conf &
xsetroot -cursor_name left_ptr &

bspc config border_width         1
bspc config focused_border_color        \#ff8700
bspc config window_gap          2
bspc config focus_follows_pointer true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_unplugged_monitors true

bspc rule -a emacs state=tiled

feh --bg-fill ~/Pictures/macos-mojave-beta5-fonds-22.jpg &
~/.config/polybar/launch.sh &
dunst -conf ~/.dunstrc &
